### ISSUE TITLE
Don't raise on bad APRS frames.

### ISSUE THREAD

**Issue by ampledata** [ampledata/aprscot#2]
```
ubuntu@ubuntu:~$ aprscot -c xxx-10 -U tcp:1.2.3.4:8088 -f 'm/200'
2021-05-14 17:52:53,641 pytak INFO - Using APRS Host: rotate.aprs.net:14580
2021-05-14 17:52:53,642 pytak INFO - Running EventTransmitter
2021-05-14 17:52:53,643 pytak INFO - Running APRSWorker
2021-05-14 17:52:53,647 pytak INFO - Running EventReceiver
2021-05-14 17:52:55,266 pytak INFO - Using APRS Filter: 'm/200'
Task completed: <Task finished name='Task-3' coro=<APRSWorker.run() done, defined at /usr/local/lib/python3.8/dist-packages/aprscot-4.0.0-py3.8.egg/aprscot/classes.py:71> exception=ParseError('invalid format')>
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<APRSWorker.run() done, defined at /usr/local/lib/python3.8/dist-packages/aprscot-4.0.0-py3.8.egg/aprscot/classes.py:71> exception=ParseError('invalid format')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aprscot-4.0.0-py3.8.egg/aprscot/classes.py", line 91, in run
    await self.handle_message(frame)
  File "/usr/local/lib/python3.8/dist-packages/aprscot-4.0.0-py3.8.egg/aprscot/classes.py", line 56, in handle_message
    aprs_frame = aprslib.parsing.parse(message)
  File "/usr/local/lib/python3.8/dist-packages/aprslib-0.6.47-py3.8.egg/aprslib/parsing/_init_.py", line 114, in parse
    _try_toparse_body(packet_type, body, parsed)
  File "/usr/local/lib/python3.8/dist-packages/aprslib-0.6.47-py3.8.egg/aprslib/parsing/_init_.py", line 204, in _try_toparse_body
    body, result = parse_position(packet_type, body)
  File "/usr/local/lib/python3.8/dist-packages/aprslib-0.6.47-py3.8.egg/aprslib/parsing/position.py", line 59, in parse_position
    raise ParseError("invalid format")
aprslib.exceptions.ParseError: invalid format
```

**Comment by koneslager** [comment]
I am having this same issue.

**Comment by ampledata** [comment]
I believe this is fixed here: https://github.com/ampledata/aprscot/blob/main/aprscot/classes.py#L54

Let me know if you're getting a different stacktrack.

**Comment by koneslager** [comment]
Is that included in the install download or does that file need to be edited?

**Comment by koneslager** [comment]
DEBUG:asyncio:<_SelectorSocketTransport fd=6 read=idle write=<idle, bufsize=0>>: Fatal write error on socket transport
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 857, in write
    n = self._sock.send(data)
ConnectionResetError: [Errno 104] Connection reset by peer
Task completed: <Task finished coro=<Worker.run() done, defined at /usr/local/lib/python3.7/dist-packages/pytak-3.5.2-py3.7.egg/pytak/classes.py:55> exception=ConnectionResetError('Connection lost') created at /usr/lib/python3.7/asyncio/tasks.py:361>
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<Worker.run() done, defined at /usr/local/lib/python3.7/dist-packages/pytak-3.5.2-py3.7.egg/pytak/classes.py:55> exception=ConnectionResetError('Connection lost') created at /usr/lib/python3.7/asyncio/tasks.py:361>
source_traceback: Object created at (most recent call last):
  File "/usr/local/bin/aprscot", line 11, in <module>
    load_entry_point('aprscot==4.0.0', 'console_scripts', 'aprscot')()
  File "/usr/local/lib/python3.7/dist-packages/aprscot-4.0.0-py3.7.egg/aprscot/commands.py", line 98, in cli
    asyncio.run(main(opts), debug=bool(os.environ.get('DEBUG')))
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1767, in _run_once
    handle._run()
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/dist-packages/aprscot-4.0.0-py3.7.egg/aprscot/commands.py", line 56, in main
    return_when=asyncio.FIRST_COMPLETED)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 361, in wait
    fs = {ensure_future(f, loop=loop) for f in set(fs)}
  File "/usr/lib/python3.7/asyncio/tasks.py", line 361, in <setcomp>
    fs = {ensure_future(f, loop=loop) for f in set(fs)}
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pytak-3.5.2-py3.7.egg/pytak/classes.py", line 65, in run
    await self.handle_event(event)
  File "/usr/local/lib/python3.7/dist-packages/pytak-3.5.2-py3.7.egg/pytak/classes.py", line 100, in handle_event
    await self.writer.drain()
  File "/usr/lib/python3.7/asyncio/streams.py", line 348, in drain
    await self._protocol._drain_helper()
  File "/usr/lib/python3.7/asyncio/streams.py", line 202, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
DEBUG:asyncio:Close <_UnixSelectorEventLoop running=False closed=False debug=True>
root@raspberrypi:/home/pi/aprscot#

**Comment by ampledata** [comment]
These two ```ConnectionResetError: [Errno 104] Connection reset by peer``` and ```ConnectionResetError: Connection lost``` Exceptions are sus.

Do you see any markers come across on your TAK client(s)? 

- If so, I'd suspect it's a network disconnect on the **aprscot** connection to APRS-IS, which it manages.
- If not, I'd suspect its **pytak**'s network connection handler that's unable to connect to your TAK client.

**Comment by ampledata** [comment]
- If it turns out that it's **aprscot** generating these messages from APRS-IS server connection 'drops', I believe the expected behavior is for **aprscot** to manage the re-try. 
- Otherwise I've plumbed it to exit the program and allow a daemon manager like systemd or supervisord to control
