### ISSUE TITLE
Issue running on Ubuntu 20.04

### ISSUE THREAD

**Issue by netsound** [ampledata/aprscot#8]
Using fresh Ubuntu 20.04 image along with the Debian/Ubuntu packages or the PIP install or even building from source with fresh images each time getting the following when trying to run the software:

aprscot -c ./aprs.ini
Traceback (most recent call last):
  File "/usr/bin/aprscot", line 11, in <module>
    load_entry_point('aprscot==5.0.5', 'console_scripts', 'aprscot')()
  File "/usr/lib/python3/dist-packages/aprscot/commands.py", line 74, in cli
    asyncio.run(main(config), debug=config["aprscot"].getboolean("DEBUG"))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3/dist-packages/aprscot/commands.py", line 39, in main
    reader, writer = await pytak.protocol_factory(cot_url)
  File "/usr/lib/python3/dist-packages/pytak/client_functions.py", line 53, in protocol_factory
    reader, writer = await asyncio.open_connection(host, port)
  File "/usr/lib/python3.8/asyncio/streams.py", line 52, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 986, in create_connection
    infos = await self._ensure_resolved(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1365, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "/usr/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

**Comment by Sn1PeR** [comment]
Rolling back to PyTak version 3.5.2 fixed this error for me.
```
git clone https://github.com/ampledata/pytak
cd pytak
pip uninstall pytak
git checkout 782742e
python setup.py install
```

**Comment by Sn1PeR** [comment]
Update: If you're on the latest version (5.0.5) of aprscot and PyTak (5.0.2), you can get multicast UDP to work by commenting COT_URL out of the aprscot config .ini. It looks like that will be set via. an environmental variable passed to PyTak now, but I haven't worked out how yet.
